version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  app:
    container_name: app
    restart: always
    environment:
      # https://stackoverflow.com/questions/43162897/how-to-connect-to-mongodb-using-docker-compose
      - DB_URI=mongodb://mongo:27017
    build: .
    ports:
      - "6000:6000"
    depends_on:
      - mongo